import type { Stream, TemplateConfig } from "@yext/pages";
import { dedupeStreamFields } from "src/common/helpers";

/**
 * Required when Knowledge Graph data is used for a template.
 */
export const configBuilder: (
  id?: string,
  filter?: Stream["filter"]
) => TemplateConfig = (id?: string, filter?: Stream["filter"]) => ({
  stream: {
    $id: id || "locations",
    // Specifies the exact data that each generated document will contain. This data is passed in
    // directly as props to the default exported function.
    fields: dedupeStreamFields([
      "id",
      "uid",
      "meta",
      "name",
      "address",
      "slug",
      "deliveryHours",
      "takeoutHours",
      "mainPhone",
      "yextDisplayCoordinate",
      "c_additionalCarryOutHoursText",
      "c_aktest",
      "c_bingMenuURL",
      "c_bingTrackingURL",
      "c_cTA1Text",
      "c_cTA1URL",
      "c_careers1",
      "c_careersCTAText",
      "c_careersClickthroughURL",
      "c_class",
      "c_contact",
      "c_conversion",
      "c_corp_Fran",
      "c_county",
      "c_del_Carry",
      "c_develop_ID",
      "c_editor",
      "c_enableTrackingTags",
      "c_fAQAnswer1",
      "c_fAQAnswer2",
      "c_fAQAnswer3",
      "c_fAQAnswer4",
      "c_fAQAnswer5",
      "c_fAQAnswer6",
      "c_fAQAnswer7",
      "c_fAQQuestion1",
      "c_fAQQuestion2",
      "c_fAQQuestion3",
      "c_fAQQuestion4",
      "c_fAQQuestion5",
      "c_fAQQuestion6",
      "c_fAQQuestion7",
      "c_fBTrackingURL",
      "c_focusPickUpHours",
      "c_franchise",
      "c_gMBMenuURL",
      "c_gMBOrderURL",
      "c_gMB_labels",
      "c_liveOnPages",
      "c_locationPageMetaDescription",
      "c_locationPageMetaTitle",
      "c_notificationBanner",
      "c_onlinePickUpHours",
      "c_openDate",
      "c_openMonth",
      "c_open_Date",
      "c_pageBusinessDescription",
      "c_pagesBusinessDescriptionCTAURL",
      "c_pagesCTA2Text",
      "c_pagesCTA2URL",
      "c_pagesCTA3Text",
      "c_pagesCTA3URL",
      "c_pagesDeals1",
      "c_pagesDeals1CTAText",
      "c_pagesDeals2",
      "c_pagesDeals2CTAText",
      "c_pagesDeals3",
      "c_pagesDeals3CTAText",
      "c_pagesFindAnotherStoreButton",
      "c_pagesGeomodifier",
      "c_pagesNotificationBanner",
      "c_pagesPromotionDescription",
      "c_pagesPromotionTitle",
      "c_pagesURL",
      "c_pixelGetDirectionsTag",
      "c_pixelOrderCarryoutTag",
      "c_pixelOrderDeliveryTag",
      "c_qCC",
      "c_requestor",
      "c_rewards",
      "c_rewardsCTAText",
      "c_rewardsCTAURL",
      "c_storeID",
      "c_storeType",
      "c_type",
      "c_unit",
      "c_up_Type",
      "c_videoPromo1",
      "c_videoPromo2",
      "c_videoPromo3",
      "c_videoSectionTitle",
      "dm_directoryParents_defaultdirectory.name",
      "dm_directoryParents_defaultdirectory.slug",
      "dm_directoryParents_defaultdirectory.meta.entityType",
      "dm_directoryParents_defaultdirectory.dm_directoryParents_defaultdirectory.name",
      "dm_directoryParents_defaultdirectory.dm_directoryParents_defaultdirectory.slug",
      "dm_directoryParents_defaultdirectory.dm_directoryParents_defaultdirectory.dm_directoryParents_defaultdirectory.name",
      "dm_directoryParents_defaultdirectory.dm_directoryParents_defaultdirectory.dm_directoryParents_defaultdirectory.slug",
    ]),
    // Defines the scope of entities that qualify for this stream.
    filter: filter || {
      entityTypes: ["location"],
    },
    // The entity language profiles that documents will be generated for.
    localization: {
      locales: ["en"],
    },
  },
});
